export default {
    card: {
        name: "Solpositionskort",
        description: "Solens och månens position med anpassade bilder."
    },
    error: {
        no_sun_entity: "Vänligen ange en sol-entitet.",
        entity_not_found: "Entitet hittades inte: "
    },
    sun_state: {
        below_horizon: "Under horisonten",
        dawn: "Gryning",
        dusk: "Skymning",
        morning: "Förmiddag",
        noon: "Middag",
        afternoon: "Eftermiddag",
        evening: "Kväll"
    },
    moon_phase: {
        new_moon: 'Nymåne',
        waxing_crescent: 'Tilltagande måne',
        first_quarter: 'Första kvarteret',
        waxing_gibbous: 'Tilltagande gibbös',
        full_moon: 'Fullmåne',
        waning_gibbous: 'Avtagande gibbös',
        last_quarter: 'Sista kvarteret',
        waning_crescent: 'Avtagande måne'
    },
    weather_state: {
        'clear-night': 'Klar natt',
        'cloudy': 'Molnigt',
        'fog': 'Dimma',
        'hail': 'Hagel',
        'lightning': 'Åska',
        'lightning-rainy': 'Åska och regn',
        'partlycloudy': 'Delvis molnigt',
        'pouring': 'Skyfall',
        'rainy': 'Regnigt',
        'snowy': 'Snöigt',
        'snowy-rainy': 'Snö och regn',
        'sunny': 'Soligt',
        'windy': 'Blåsigt',
        'windy-variant': 'Blåsigt',
        'exceptional': 'Extremt'
    },
    time_entry: {
        current: "Nuvarande",
        azimuth: "Azimut",
        elevation: "Elevation",
        daylight_duration: "Dagens längd",
        day_comparison: "Jämförelse av dagslängd",
        next_rising: "Soluppgång",
        next_setting: "Solnedgång",
        next_dawn: "Gryning",
        next_dusk: "Skymning",
        next_noon: "Middag",
        next_midnight: "Midnatt",
        moon_phase: "Månfas",
        weather: "Väder"
    },
    editor: {
        entity: "Sol-entitet",
        moon_entity: "Mån-entitet (valfri)",
        weather_entity: "Väder-entitet (valfri)",
        temp_entity: "Temperatur-entitet (valfri, ersätter väder)",
        main_options: "Visningsalternativ",
        view_mode: "Visningsläge",
        view_mode_classic: "Klassisk (6 bilder)",
        view_mode_calculated: "Beräknad (endast elevation)",
        view_mode_arc: "Båge (180° rörelse)",
        show_image: "Visa solposition (bild)",
        show_weather_badge: "Visa väderindikator",
        animate_images: "Animera bilder (förutom morgon/skymningsbild)",
        sun_size: "Sol/Måne-storlek (endast båge)",
        state_position: "Statusposition",
        state_pos_above: "Ovanför bild",
        state_pos_in_list: "I lista",
        state_pos_hide: "Dölj",
        moon_phase_position: "Månfasposition",
        hide_moon_phase_on_day: "Dölj månfas under dagen",
        show_night_arc: "Visa månbåge (180°)",
        show_moon_icon_in_text: "Visa månikon i text",
        show_dividers: "Visa avdelare",
        show_degrees: "Visa grader (azimut/elevation)",
        show_degrees_in_list: "Visa grader i lista",
        time_position: "Tidsposition",
        time_pos_below: "Under bild",
        time_pos_above: "Ovanför bild",
        time_pos_right: "Till höger om bild",
        time_list_format: "Justering av tidslista",
        time_format_centered: "Centrerad",
        time_format_block: "Block",
        times_to_show: "Välj tider",
        use_12h_format: "Använd 12-timmarsformat (AM/PM)",
        language: "Språk",
        language_auto: "Automatiskt (Home Assistant)",
        solar_entity: "Solenergi-entitet (valfri, t.ex. vädersensor)",
        show_solar_badge: "Visa solenergi-indikator",
        advanced_options: "Tröskelvärden (avancerat)",
        morning_azimuth: "Morgon-azimut",
        noon_azimuth: "Middag-azimut",
        afternoon_azimuth: "Eftermiddags-azimut",
        dusk_elevation: "Skymnings-elevation"
    }
};
