export default {
    card: {
        name: "Cartão de Posição Solar",
        description: "Posição do Sol e da Lua com imagens personalizadas."
    },
    error: {
        no_sun_entity: "Por favor, defina uma entidade solar.",
        entity_not_found: "Entidade não encontrada: "
    },
    sun_state: {
        below_horizon: "Abaixo do Horizonte",
        dawn: "Amanhecer",
        dusk: "Entardecer",
        morning: "Manhã",
        noon: "Meio-dia",
        afternoon: "Tarde",
        evening: "Noite"
    },
    moon_phase: {
        new_moon: 'Lua Nova',
        waxing_crescent: 'Lua Crescente',
        first_quarter: 'Quarto Crescente',
        waxing_gibbous: 'Gibosa Crescente',
        full_moon: 'Lua Cheia',
        waning_gibbous: 'Gibosa Minguante',
        last_quarter: 'Quarto Minguante',
        waning_crescent: 'Lua Minguante'
    },
    weather_state: {
        'clear-night': 'Noite Limpa',
        'cloudy': 'Nublado',
        'fog': 'Névoa',
        'hail': 'Granizo',
        'lightning': 'Raios',
        'lightning-rainy': 'Chuva com Raios',
        'partlycloudy': 'Parcialmente Nublado',
        'pouring': 'Chuva Forte',
        'rainy': 'Chuvoso',
        'snowy': 'Nevando',
        'snowy-rainy': 'Chuva e Neve',
        'sunny': 'Ensolarado',
        'windy': 'Ventania',
        'windy-variant': 'Vento Variável',
        'exceptional': 'Excepcional'
    },
    time_entry: {
        current: "Atual",
        azimuth: "Azimute",
        elevation: "Elevação",
        daylight_duration: "Duração da Luz do Dia",
        day_comparison: "Comparação de Luz Solar",
        next_rising: "Nascer do Sol",
        next_setting: "Pôr do Sol",
        next_dawn: "Alvorecer",
        next_dusk: "Crepúsculo",
        next_noon: "Meio-dia solar",
        next_midnight: "Meia-noite",
        moon_phase: "Fase da Lua",
        weather: "Clima"
    },
    editor: {
        entity: "Entidade Solar",
        moon_entity: "Entidade Lunar (Opcional)",
        weather_entity: "Entidade de Clima (Opcional)",
        temp_entity: "Entidade de Temperatura (Opcional, substitui clima)",
        main_options: "Opções de Exibição",
        view_mode: "Modo de Visualização",
        view_mode_classic: "Clássico (6 Imagens)",
        view_mode_calculated: "Calculado (Apenas elevação)",
        view_mode_arc: "Arco (Movimento 180°)",
        show_image: "Mostrar Posição do Sol (Imagem)",
        show_weather_badge: "Mostrar Badge de Clima",
        animate_images: "Animar Imagens (exceto imagem de manhã/crepúsculo)",
        sun_size: "Tamanho do Sol/Lua (Apenas Arco)",
        state_position: "Posição do Estado",
        state_pos_above: "Acima da Imagem",
        state_pos_in_list: "Na Lista",
        state_pos_hide: "Ocultar",
        moon_phase_position: "Posição da Fase da Lua",
        hide_moon_phase_on_day: "Ocultar Fase da Lua durante o dia",
        show_night_arc: "Mostrar Arco da Lua (180°)",
        show_moon_icon_in_text: "Mostrar Ícone da Lua no texto",
        show_dividers: "Mostrar Divisores",
        show_degrees: "Mostrar Graus (Azimute/Elevação)",
        show_degrees_in_list: "Mostrar Graus na Lista",
        time_position: "Posição do Horário",
        time_pos_below: "Abaixo da Imagem",
        time_pos_above: "Acima da Imagem",
        time_pos_right: "À Direita da Imagem",
        time_list_format: "Alinhamento da Lista de Horários",
        time_format_centered: "Centralizado",
        time_format_block: "Bloco",
        times_to_show: "Selecionar Horários",
        use_12h_format: "Usar formato 12 horas (AM/PM)",
        language: "Idioma",
        language_auto: "Automático (Home Assistant)",
        solar_entity: "Entidade de Energia Solar (Opcional, ex: sensor de clima)",
        show_solar_badge: "Mostrar Badge de Energia Solar",
        advanced_options: "Limites (Avançado)",
        morning_azimuth: "Azimute da Manhã",
        noon_azimuth: "Azimute do Meio-dia",
        afternoon_azimuth: "Azimute da Tarde",
        dusk_elevation: "Elevação do Entardecer"
    }
};
